apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: aura
  annotations:
    nais.io/naisjob: "true"
  name: oh-no-unscheduled
  namespace: aura
spec:
  image: navikt/perl
  command: ["perl", "-le", "sleep(40);print 'job complete'"]
  secureLogs:
    enabled: true
